"""Per-scene Goal definitions for GCD.

One Goal = (target_y, tolerance, control_range, overlay_type, description).

We deliberately keep target_y as the *hidden* observable value; the agent
never sees it in numeric form. The agent sees only the rendered scene with
a green target object placed at the corresponding world location, and
gets PASS/FAIL + a visual residual after each attempt.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

OverlayType = Literal["position", "scalar", "phase"]


@dataclass
class Goal:
    view_id: str                # e.g. "s1_freefall"
    slug: str                   # underlying scenario slug
    name: str                   # short human label, e.g. "Drop Catcher"
    overlay_type: OverlayType
    target_y: float             # ground-truth observable value the agent must hit
    tolerance: float            # epsilon, in same units as target_y
    control_range: tuple[float, float]  # safety bounds for the agent's chosen u
    difficulty: Literal["easy", "medium", "hard"] = "easy"
    units: str = ""             # display only, e.g. "m", "deg", "C"
    description: str = ""       # natural-language goal for the agent prompt


# ---------------------------------------------------------------------------
# Pool generation rule (kept inline as pure data, not generated at import):
#   - 5 hold-out goals per view, all OUTSIDE the training control range,
#     stratified as 2 easy / 2 medium / 1 hard.
#   - target_y is computed from CF alpha (see DEFAULT_COUNTERFACTUALS).
#   - tolerance defaults to 5% of |target_y| unless physics demands otherwise.
#
# This file is the SOURCE OF TRUTH for the goal pool. The actual numeric
# target_y values can be (re)generated by `solver.materialize_goal_pool()`,
# but we ship a static pool so eval is deterministic across machines.
# ---------------------------------------------------------------------------

# For brevity: only 1 sample goal per view shown here. The full 5-per-view
# table is materialized by `materialize_goal_pool()` on first run and
# cached to `goals/_pool_cache.json`.
GOAL_POOL: dict[str, list[Goal]] = {
    "s1_freefall":   [],   # Drop Catcher    — position
    "s2_mass":       [],   # Drop Catcher m=3 — position
    "s3_pendulum":   [],   # Bell Strike     — position
    "s4_ramp":       [],   # Ramp Catcher    — position
    "s6_launch":     [],   # Hoop Shot       — position
    "s8_heat":       [],   # Thermometer Match — scalar
    "s9_spring":     [],   # Trigger Plate   — position
    "s10_circular":  [],   # Rendezvous      — phase
    "s16_decay":     [],   # Half-Life Hit   — scalar
    "s17_refraction":[],   # Underwater Tgt  — position
    "s18_boyle":     [],   # Piston Mark     — position
    "s19_coulomb":   [],   # Repulsion Dist  — position
    "s20_hooke":     [],   # Stretch to Mark — position
    "s21_weber":     [],   # Glow Match      — scalar
    "s22_cooling":   [],   # Cool-Down Time  — scalar
}


# Per-view metadata. The GCD-phase agent works the SAME control variable
# the discovery-phase agent works (`scenario.meta.control_var`); we keep
# the field name `gcd_control` for clarity but its value must match the
# scenario's real control_var so the oracle, the runner, and the prompt
# all agree on what u* means.
#
# `goal_kind` selects the green-marker style drawn by `draw_goal_marker`.
# `goal_kind = None` means scalar/phase scenes that don't need an
# in-scene marker (overlay_scalar/phase handle the visualisation).
VIEW_GOAL_META: dict[str, dict] = {
    "s1_freefall":    {"overlay": "position", "name": "Drop Catcher",       "gcd_control": "max_t",              "units": "m",     "goal_kind": "cart"},
    "s2_mass":        {"overlay": "position", "name": "Drop Catcher (m=3)", "gcd_control": "max_t",              "units": "m",     "goal_kind": "cart"},
    "s3_pendulum":    {"overlay": "position", "name": "Bell Strike",        "gcd_control": "length_m",           "units": "s",     "goal_kind": "bell"},
    "s4_ramp":        {"overlay": "position", "name": "Ramp Catcher",       "gcd_control": "max_t",              "units": "m",     "goal_kind": "cart"},
    "s6_launch":      {"overlay": "position", "name": "Hoop Shot",          "gcd_control": "speed_mps",          "units": "m",     "goal_kind": "hoop"},
    "s8_heat":        {"overlay": "scalar",   "name": "Thermometer Match",  "gcd_control": "time_s",             "units": "m",     "goal_kind": None},
    "s9_spring":      {"overlay": "position", "name": "Trigger Plate",      "gcd_control": "mass_kg",            "units": "m",     "goal_kind": "piston_line"},
    "s10_circular":   {"overlay": "phase",    "name": "Rendezvous",         "gcd_control": "semi_major_axis",    "units": "yr",    "goal_kind": None},
    "s16_decay":      {"overlay": "scalar",   "name": "Half-Life Hit",      "gcd_control": "time",               "units": "frac",  "goal_kind": None},
    "s17_refraction": {"overlay": "position", "name": "Underwater Target",  "gcd_control": "angle_incidence_deg","units": "deg",   "goal_kind": "underwater_target"},
    "s18_boyle":      {"overlay": "position", "name": "Piston Mark",        "gcd_control": "pressure_atm",       "units": "cm",    "goal_kind": "piston_line"},
    "s19_coulomb":    {"overlay": "position", "name": "Repulsion Distance", "gcd_control": "distance",           "units": "N",     "goal_kind": "mark"},
    "s20_hooke":      {"overlay": "position", "name": "Stretch to Mark",    "gcd_control": "mass_kg",            "units": "m",     "goal_kind": "piston_line"},
    "s21_weber":      {"overlay": "scalar",   "name": "Glow Match",         "gcd_control": "temperature",        "units": "nm",    "goal_kind": None},
    "s22_cooling":    {"overlay": "scalar",   "name": "Cool-Down Timing",   "gcd_control": "time",               "units": "C",     "goal_kind": None},
}


def get_goals(view_id: str) -> list[Goal]:
    """Return the hold-out goal list for a given view_id."""
    return GOAL_POOL.get(view_id, [])
